---
title: "  ZAMAR|SPACE"
subtitle: "Hub Rzeczy Różnych"
format: 
  html:
    toc: false
    #scss: styles.css
    theme: cosmo
---

# Wirtualna przestrzeń dla pojektów pisanych do szuflady na później. Enjoy {.unnumbered}
  
<br>


<div class="welcome-content">
  <p>
    Witaj w <strong>ZAMARSPACE</strong> – wirtualnej przestrzeni dedykowanej różnorodnym projektom programistycznym. Programuję w języku R, wykorzystując jego pełne możliwości, w tym framework <strong>Shiny</strong>, tworząc narzędzia analityczne dedykowane obszarowi farmacji i medycyny.
  </p>
  
  <p>
    Projekty prezentowane tutaj mogą zawierać błędy, niedociągnięcia składni czy słabe formatowanie, ponieważ zostały stworzone z myślą o własnych potrzebach i są ciągle rozwijane.
  </p>
  
  <p>
    Projekt jest **open-source**. Zapraszam do eksploracji moich zasobów, korzystania z aplikacji oraz materiałów edukacyjnych dostępnych na tej stronie. Jeśli masz pytania lub chciałbyś nawiązać współpracę, nie wahaj się skontaktować!
  </p>
</div>

